# Use postgres/example user/password credentials
version: "3.9"

services:
  pg:
    image: postgres:17-alpine
    hostname: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: main_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
